### ISSUE TITLE
CFURLCreateStringByAddingPercentEscapes in GTMNSString+URLArguments.m issues warnings with iOS 9 SDK

### ISSUE THREAD

**Issue by Arcank** [google/google-toolbox-for-mac#105]
This is used in https://github.com/google/google-toolbox-for-mac/blob/master/Foundation/GTMNSString%2BURLArguments.m

When building with iOS 9, this issues these warnings:
../../third_party/google_toolbox_for_mac/src/Foundation/GTMNSString+URLArguments.m:27:5: warning: 'CFURLCreateStringByAddingPercentEscapes' is deprecated: first deprecated in iOS 9.0 - Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid). [-Wdeprecated-declarations]
    CFURLCreateStringByAddingPercentEscapes(kCFAllocatorDefault,
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:395:13: note: 'CFURLCreateStringByAddingPercentEscapes' has been explicitly marked deprecated here
CFStringRef CFURLCreateStringByAddingPercentEscapes(CFAllocatorRef allocator, CFStringRef originalString, CFStringRef charactersToLeaveUnescaped, CFStringRef legalURLCharactersToBeEscaped, CFStringEncoding encoding) CF_DEPRECATED(10_0, 10_11, 2_0, 9_0, "Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).");
            ^
../../third_party/google_toolbox_for_mac/src/Foundation/GTMNSString+URLArguments.m:45:24: warning: 'stringByReplacingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByRemovingPercentEncoding instead, which always uses the recommended UTF-8 encoding. [-Wdeprecated-declarations]
  return [resultString stringByReplacingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURL.h:529:1: note: 'stringByReplacingPercentEscapesUsingEncoding:' has been explicitly marked deprecated here
- (nullable NSString *)stringByReplacingPercentEscapesUsingEncoding:(NSStringEncoding)enc NS_DEPRECATED(10_0, 10_11, 2_0, 9_0, "Use -stringByRemovingPercentEncoding instead, which always uses the recommended UTF-8 encoding.");
  ^
  2 warnings generated.

**Comment by thomasvl** [comment]
If your minimum os is high enough to trigger these warnings, you should be able to use the newer Foundation apis for url arguments directly and not need these helpers. When GTM moves it's minimum generally high enough that those apis always exist, we'll remove the helpers as they aren't needed.
