### ISSUE TITLE
GTMWindowSheetController and switching between multiple sheets in macOS Sierra

### ISSUE THREAD

**Issue by lemonmojo** [google/google-toolbox-for-mac#123]
I'm using GTMWindowSheetController in my Mac app [Royal TSX](https://www.royalapplications.com/ts/osx) to display tab-modal sheets.
It's been working perfectly fine since Snow Leopard but since Sierra I'm having an issue with multiple sheets.

If I open more than one sheet only the last one opened will react to mouse clicks. Keyboard interaction is still working but as soon as I switch away from the last opened sheet, any mouse events are ignored.

The only workaround I was able to come up with is to always set `ignoresMouseEvents` on the overlay window to `YES` when switching between active views in `setActiveView:`.
Obviously this has the unfortunate side effect of allowing clicks to go through the overlay window and to the views behind it.

Is anyone having the same issue and know what's causing it or even have a better workaround or fix?

**Comment by thomasvl** [comment]
Closing this since we're dropping it.  Chrome was the original use case for this (and the contributors), but we never got some followup on this issue when it was first raised/relayed.  Sorry.
