### ISSUE TITLE
The app references non-public selectors in {$APPName}: _terminateWithStatus:

### ISSUE THREAD

**Issue by LSsoftware** [google/google-toolbox-for-mac#130]
i recently got a problem 'The app references non-public selectors in {$APPName}: _terminateWithStatus:'
Will I get an error when I change this selector.

**Comment by thomasvl** [comment]
What's calling that selector?  It was used in some unittesting code, but you shouldn't be linking that into your final application as it is only for testing.

**Comment by bensmiley** [comment]
I'm including the GoogleToolboxForMac as part of the Google Firebase CocoaPods. How am I supposed to stop it linking in the final build?

**Comment by sergiocampama** [comment]
@bensmiley  can you provide a sample project with Cocoapods configured that displays this behavior?

**Comment by bensmiley** [comment]
@sergiocampama Yes, you can see the full project [https://github.com/chat-sdk/chat-sdk-ios](url)

**Comment by thomasvl** [comment]
As we saw in #138 so other pods are pulling in everything instead of just the subset they need, which means they are picking up some testing only code.  So odds are something in that deps chain has an overly board dependency.

**Comment by bensmiley** [comment]
I resolved the issue. It turned out that Firebase only needed the following sub-module (initially I didn't realise that the Google toolbox contained multiple subspecs): 

```
  s.dependency 'GoogleToolboxForMac/NSData+zlib', '~>2.1.1'
```

But in the future, it may be useful to remove the module that includes the private API call from the default podspec. So when a user just adds the following line:

```
s.dependency 'GoogleToolboxForMac', '~>2.1.1'
```

The app will still pass the Apple review procedure.

**Comment by thomasvl** [comment]
Was it your spec or Firebase's that had the error?  i.e. - do we need to file an issue on Firebase to correct their usage?  (or atleast correct some docs they might have?)

I'd missed `default_subspecs` before, I could have sworn they only supported a single one which didn't work well for things like GTM.

**Comment by NabinRai4017** [comment]
Im having issue like this.

Non-public API usage:

    The app references non-public selectors in Frameworks/GoogleToolboxForMac.framework/GoogleToolboxForMac: _terminateWithStatus:

**Comment by thomasvl** [comment]
Are you using pods?  What version?  What subspecs are you using?  As mentioned before, sounds like you are pulling in the unittesting support which shouldn't be used in final apps.
