### ISSUE TITLE
duplicate error - libGoogleToolboxForMac.a(GTMLogger.o) and GoogleOpenSource(GTMLogger.o)

### ISSUE THREAD

**Issue by hyunzlife** [google/google-toolbox-for-mac#132]
**1.I built ios as Unity.**

**2.Pod installation.**

# Uncomment this line to define a global platform for your project
platform :ios, ‘9.2’

target 'Unity-iPhone' do
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'Firebase/Messaging'

    pod 'GooglePlayGames'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

**3.The following error occurred when building xcode.**

Showing All Messages
Ld /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/lottoday normal arm64
    cd /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B
    export IPHONEOS_DEPLOYMENT_TARGET=9.2
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -L/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos -L/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B -L/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Libraries -L/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Libraries/Plugins/iOS/Firebase -L/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Libraries/Plugins/iOS -L/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GTMSessionFetcher -L/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GooglePlayGames -L/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac -L/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GoogleAuthUtilities/Libraries -L/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GoogleSignIn/Libraries -F/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/FirebaseAnalytics/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/FirebaseAuth/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/FirebaseCore/Frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/FirebaseInstanceID/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/FirebaseMessaging/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GoogleAppUtilities/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GoogleInterchangeUtilities/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GoogleNetworkingUtilities/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlayGames/gpg-cpp-sdk/ios -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1 -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GoogleSymbolUtilities/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GoogleUtilities/Frameworks/frameworks -filelist /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/lottoday.LinkFileList -Xlinker -map -Xlinker /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/lottoday-LinkMap-normal-arm64.txt -miphoneos-version-min=9.2 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/lottoday_lto.o -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -lc++ -weak_framework CoreMotion -weak-lSystem -ObjC -std=gnu++11 -lGIPNSURL+FIFE -lGTMOAuth2_external -lGTMOAuth2_internal -lGTMSessionFetcher -lGooglePlayGames -lGoogleToolboxForMac -lSignIn -lc++ -lsqlite3 -lz -framework AddressBook -framework AssetsLibrary -framework CoreData -framework CoreGraphics -framework CoreLocation -framework CoreMotion -framework CoreTelephony -framework CoreText -framework FirebaseAnalytics -framework FirebaseAuth -framework FirebaseCore -framework FirebaseInstanceID -framework FirebaseMessaging -framework GoogleAppUtilities -framework GoogleInterchangeUtilities -framework GoogleNetworkingUtilities -framework GoogleOpenSource -framework GoogleSymbolUtilities -framework GoogleUtilities -framework MediaPlayer -framework QuartzCore -framework SafariServices -framework Security -framework StoreKit -framework SystemConfiguration -framework gpg -framework Security -liPhone-lib -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework MediaPlayer -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lAuth -lAnalytics -lVuforia -lMessaging -lApp -lVuforiaUnityPlayer -framework StoreKit -framework GameKit -weak_framework Metal -lPods-Unity-iPhone -Xlinker -dependency_info -Xlinker /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/lottoday_dependency_info.dat -o /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/lottoday

ld: warning: arm64 function not 4-byte aligned: ltmp0 from /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
duplicate symbol __Z18RegisterAllClassesv in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/RegisterMonoModules.o
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/UnityClassRegistration.o
duplicate symbol __Z43InvokeRegisterStaticallyLinkedModuleClassesv in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/RegisterMonoModules.o
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/UnityClassRegistration.o
duplicate symbol __Z39RegisterStaticallyLinkedModulesGranularv in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/RegisterMonoModules.o
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/UnityClassRegistration.o
duplicate symbol __Z32RegisterAllStrippedInternalCallsv in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/RegisterMonoModules.o
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/UnityICallRegistration.o
duplicate symbol _OBJC_IVAR_$_GTMLogger.formatter_ in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_IVAR_$_GTMLogger.filter_ in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_IVAR_$_GTMLogger.writer_ in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_IVAR_$_GTMLogStandardFormatter.dateFormatter_ in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_IVAR_$_GTMLogStandardFormatter.pname_ in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_IVAR_$_GTMLogStandardFormatter.pid_ in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_IVAR_$_GTMLogAllowedLevelFilter.allowedLevels_ in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_CLASS_$_GTMLogStandardFormatter in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_METACLASS_$_GTMLogStandardFormatter in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_CLASS_$_GTMLogBasicFormatter in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_CLASS_$_GTMLogLevelFilter in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_METACLASS_$_GTMLogLevelFilter in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_METACLASS_$_GTMLogBasicFormatter in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_CLASS_$_GTMLogMaximumLevelFilter in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_METACLASS_$_GTMLogMaximumLevelFilter in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_CLASS_$_GTMLogAllowedLevelFilter in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_CLASS_$_GTMLogMininumLevelFilter in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_METACLASS_$_GTMLogMininumLevelFilter in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_CLASS_$_GTMLogNoFilter in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_METACLASS_$_GTMLogNoFilter in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_CLASS_$_GTMLogger in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_METACLASS_$_GTMLogger in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol _OBJC_METACLASS_$_GTMLogAllowedLevelFilter in:
    /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
    /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
ld: 27 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**4.I need help how to solve it.**

**Comment by hyunzlife** [comment]
Removing GTMLogger has been fixed.

**Comment by seecahkhing** [comment]
I'm still encountering this issue...

**Comment by thomasvl** [comment]
Have you tried opening issues against Unity and Firebase?  Since it sounds like one of them is pre compiling the source into their app and not using a pod dependency to get it?  There isn't much we can do about it since it sounds like someone consuming our code is causing it.
