### ISSUE TITLE
ld: library not found for -lGoogleToolboxForMac

### ISSUE THREAD

**Issue by vinaygiri** [google/google-toolbox-for-mac#137]
Hi,
 
I have included file libGoogleToolboxForMac.a file in library but its showing red, and project giving me the error 
"ld: library not found for -lGoogleToolboxForMac
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

please help me regarding this

thanks

**Comment by thomasvl** [comment]
It's sorta hard to know what's wrong from that information.  The red indicates the file isn't found, so try double checking where the reference you added points too?

**Comment by vinaygiri** [comment]
I am not able to find that file, that file is not exist, from where can i get that file

**Comment by thomasvl** [comment]
From your description it sounds like you where using a build output and you had added that to your project.  Without seeing your project it's sorta hard to tell what you did to understand the error.

> I have included file libGoogleToolboxForMac.a file in library but its showing red

So what did you do for this?  Was this not a _Add files…_ operation or drag/drop to add to your project?

**Comment by srhan55ff** [comment]
srhan55ff@gmail.com

**Comment by vinaygiri** [comment]
ld: library not found for -lGoogleToolboxForMac
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have got this error after adding pod

**Comment by eduarduamaral** [comment]
Hi, this is the same problem that appears to me. But only with the debug target in production does it work.

This is my Podfile

`source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.2'
target 'MyProject' do
	pod 'OpenSSL-Universal', '1.0.1.k'
	pod 'Google'
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
end

target 'MyProject DEV' do
	pod 'OpenSSL-Universal', '1.0.1.k'
	pod 'Google'
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
end

target 'MyProjectTests' do
	pod 'OpenSSL-Universal', '1.0.1.k'
	pod 'Google'
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
end`

**Comment by Mathling** [comment]
[!] Please close any current Xcode sessions and use MyApp.xcworkspace for this project from now on.

**Comment by drailanjohngss** [comment]
Im running on myapp.xcworkspace but im still getting this error.

**Comment by eduarduamaral** [comment]
My problem was solved by changing the target of the project, my project by default is targeting MacOS, I changed it to iOS (iPhone) and my problem was solved. Thank's!!

**Comment by RameshSain** [comment]
Showing All Messages
ld: library not found for -lGTMSessionFetcher

**Comment by ShafiqEssani** [comment]
Its working when Im using MyApp.xcworkspace the build is succeeding and running on device.
but when I'm trying to archive it for uploading the IPA to Appstore, it says build failed with same error of ld: library not found for -lGoogleToolboxForMac
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please help someone!

**Comment by elhamzaouiaymen** [comment]
@Mathling thank you very much. YOU ROCK !!!!!!

**Comment by tejasparekh** [comment]
@ShafiqEssani follow these steps 
1. Remove podfile & pod.lock file
2. Add pod file configuration required.
3. Run Pod Install

**Comment by pawanline** [comment]
@ShafiqEssani  thanks man .You saved my complete whole  day.

**Comment by deblinaalways** [comment]
Go to : target -> Build Settings -> Other Linker Flags -> remove framework "GoogleToolboxforMAC" and build the project.

**Comment by dicer2000** [comment]
@deblinaalways => How do I remove that?  I see it in my Linker Flags, but it is "Resolved" and grayed out.  Thanks

**Comment by Xample** [comment]
@tejasparekh 
In my case I only had to do a 
```bash
pod install
```
in the same directory as the `podfile` of course
This installed al the dependencies (which included the lGoogleToolboxForMac)

**Comment by akkivinaya** [comment]
@ShafiqShams Hi Safiq
I am facing the same problem,I am able to run my project in simulator but while archiving it,I am getting the above mentioned error?
Do you remember how you resolved it.
Thanks to you in advance !

**Comment by akkivinaya** [comment]
@vinaygiri how did you solve the issue?
I am also facing ther same and stuck with it.
Any help will be appreciated !thanks in advance..

**Comment by akkivinaya** [comment]
> 
> 
> Its working when Im using MyApp.xcworkspace the build is succeeding and running on device.
> but when I'm trying to archive it for uploading the IPA to Appstore, it says build failed with same error of ld: library not found for -lGoogleToolboxForMac
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> Please help someone!
