### ISSUE TITLE
Non-public API usage:  The app references non-public selectors: _terminateWithStatus

### ISSUE THREAD

**Issue by pwbs** [google/google-toolbox-for-mac#138]
Apparently Apple doesn't like the use of `_terminateWithStatus` in https://github.com/google/google-toolbox-for-mac/blob/master/UnitTesting/GTMIPhoneUnitTestDelegate.m

The email I just received:

> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "XXX". To process your delivery, the following issues must be corrected:
> 
> Non-public API usage:
> 
> The app references non-public selectors in XXX: _terminateWithStatus:
> If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.
>
> If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's nine-digit Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information page.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.
> 
> Regards,
> 
> The App Store team

Then I did `sed -i  's/_terminateWithStatus/_terminateWithStatusX/g' platforms/ios/Pods/GoogleToolboxForMac/UnitTesting/GTMIPhoneUnitTestDelegate.m` and now Apple's happy with it...

I'm not sure what to do about it, but adding that `X` is probably not the right move.

**Comment by sergiocampama** [comment]
That file is meant to be used only for tests, it should not be compiled and linked into an app and sent to Apple.

**Comment by pwbs** [comment]
> That file is meant to be used only for tests, it should not be compiled and linked into an app and sent to Apple.

Makes sense. Then I have to figure out how to avoid having it compiled and linked...

I'm sure other people will run into this trouble though.

**Comment by thomasvl** [comment]
It has come up before (#130), but we haven't heard how folks added the dependency on their main app instead of just for tests.

**Comment by pwbs** [comment]
I met this issue when I switched from cordova iOS 4.3 to [4.4.0](https://cordova.apache.org/announcements/2017/04/26/ios-release.html) earlier today, so I'm guessing that the dependency has to be automatically generated by cordova (or one of the cordova plugins I use).

**Comment by ishaq-bhojani** [comment]
@pwbs Facing the same issue.
Did you find any solution for this?

**Comment by pwbs** [comment]
@ishaq-bhojani since it's not meant to be linked anyway, what you can do is to simply delete it...

I didn't investigate why cordova puts it there and makes it be embedded in the app, nor how to fix cordova for it to stop doing it...

**Comment by RTK** [comment]
I add the GoogleToolboxForMac via pod and got rejected for this issue as well. I modified the method's name locally but this is not the solution I am going for. Is there any way to solve this problem without manual deletion of the file?

**Comment by thomasvl** [comment]
Since it sounds like the problem is with something else using this pod (cordova?), has anyone reported the problem to them?  As far as I know, there isn't really something we can do as they are the ones forcing the dependency in non testing code.

**Comment by pwbs** [comment]
I just opened an issue at Cordova's: https://issues.apache.org/jira/browse/CB-12843

**Comment by pwbs** [comment]
Apparently it's coming from `phonegap-plugin-push`.
https://github.com/phonegap/phonegap-plugin-push/pull/1736#issuecomment-303905382
