### ISSUE TITLE
iOS : GTMNSString+HTML.h category functions not called

### ISSUE THREAD

**Issue by neerajvenugl** [google/google-toolbox-for-mac#142]
I am currently working on iOS , I was using this GTMNSString+HTML file .h/.m for removing html tags from string, but after integration of mobilevision framework the function of "gtm_stringByUnescapingFromHTML" is not being called from the application . Is it because the GoogleVision api uses it as a wrapper on some other file.

What is the alternative to use gtm_stringByUnescapingFromHTML apart from renaming the function  in the category file "GTMNSString+HTML.h"

**Comment by thomasvl** [comment]
Sounds like you should open an issue on that other framework and suggest they document and expose it or they support pulling the the dependency on it form GTM (possibly directly with cocoapods).  There isn't much we can do when other folks embed copies of the code.

To solve it on your own, yes, you'd have to copy the source, and rename the copy you want to use if you aren't sure about what their version does.

**Comment by neerajvenugl** [comment]
Thanks for the quick reply , yes I had renamed it and after that it works perfect . Thanks a lot for your comments and your views.
