### ISSUE TITLE
Update Podspec

### ISSUE THREAD

**Issue by levigroker** [google/google-toolbox-for-mac#148]
The current pod release, 2.1.1, does not include changes made which allow GTM to be compatible with macOS 10.12. Specifically, in `GTMSystemVersion.m` the change from `require_noerr` to `__Require_noErr`.

Please create a new pod version which includes the (more) recent changes so GTM can be built against the latest macOS SDK.

**Comment by thomasvl** [comment]
Thanks for the reminder, didn't realized we'd gone that long without doing a release.  I just pushed v1.2.2, but it still kicks out a few warnings under Xcode 9.  I'll try to fix those in the near future.

**Comment by levigroker** [comment]
Thanks @thomasvl!

**Comment by thomasvl** [comment]
Fyi #150 adds more fixes, I guess I'll do a v2.1.3 to remove the warnings from the pod.

**Comment by levigroker** [comment]
Thank you @thomasvl. That would be appreciated.

**Comment by thomasvl** [comment]
Done.  #152 is for the last set of things I wasn't able to knock out right now.

**Comment by levigroker** [comment]
Cheers.
