### ISSUE TITLE
GTMNSString+URLArguments.m kicks out some warnings on newer Xcodes/SDKs

### ISSUE THREAD

**Issue by thomasvl** [google/google-toolbox-for-mac#152]
Some of the APIs being used under the hood are now deprecated, so we need to go back and add the right conditionals to the calls so when using a high enough min, it does't create any warnings.

**Comment by dmaclach** [comment]
See https://github.com/google/google-toolbox-for-mac/pull/198 which deprecates all of these calls.

**Comment by thomasvl** [comment]
Closing since the better path is for folks to move off the GTM helper when they have a higher min OS version.
