### ISSUE TITLE
Italics are not supported in HTML conversion category

### ISSUE THREAD

**Issue by deepu462** [google/google-toolbox-for-mac#153]
I tried adding the category GTMNString+HTML to my classes and the encoded html string had tags which were to be shown in _Italics_ and **Bold**. Unfortunately those tag are not getting recognized. Can someone please throw some light on that issue?

**Comment by thomasvl** [comment]
I'm not sure what you mean, you have to call the methods to have a string transformed (escaped).  What did you actually do?

**Comment by deepu462** [comment]
I am trying to convert an html encoded string that has Italics and Bold tags.. say example 

> &lt;i&gt;&amp;ldquo; Ah the joys of the

Now i am using the method to decode the above text and it should return me the text in italics. But i am getting a plain text.. So i wanted to convert the text which has html tags and show it in my screen. Any help on this?

**Comment by thomasvl** [comment]
Sorry, still not following.  GTMNString+HTML has methods to escape html or unescape it.  It is nothing about rendering.

**Comment by deepu462** [comment]
Ok. This is it. I am getting a text from a response which is encoded. Now i want to decode the text and show it in my textview. In the process i am using the method **gtm_stringByUnescapingFromHTML** to decode the encoded text that i am getting from server. But the problem here is, some parts of the text which has italics and bold text is not getting displayed. I am looking out for help on how to show the text in italics and bold.

**Comment by thomasvl** [comment]
From the sound of that, you shouldn't be using GTMNString+HTML at all.  It sounds like you are saying the text is already html.  GTMNString+HTML is to convert the the "<", ">", "&" characters to and from HTML entities.

If all you want is to display html in your UI.  I'd suggest you do some search for something like "display html in NSTextView" or "display html in UILabel" depending on what platforms you are trying to do this.  There are lots of answers out there.

**Comment by hendra4ditya** [comment]
IRS 990s "GLOBAL COMPACT PONDATION" EIN (ID:16-1756484) userid.brightstar.co.id
