### ISSUE TITLE
gtm_stringByUnescapingFromHTML does not unescape &#128077;

### ISSUE THREAD

**Issue by salagadoola** [google/google-toolbox-for-mac#155]
I was trying to unescape `&#128077;` (which is &#128077;), but found that gtm_stringByUnescapingFromHTML could only unescape number sequence below 65535 (USHRT_MAX).

Is is possible to support unescaping HTML entities above 65535 and make `XCTAssertEqualObjects([@"&#128077;" gtm_stringByUnescapingFromHTML], @"👍", @"HTML unescaping failed");` pass?

Edit:
I am thinking of solving this issue with https://github.com/salagadoola/google-toolbox-for-mac/commit/c28a73bb35b704b54f66dfa89bc5286e26738dac which is derived from stackoverflow https://stackoverflow.com/questions/6458708/converting-an-nsstring-to-and-from-utf32#answer-6458988

**Comment by thomasvl** [comment]
That looks fine, feel free to send in a Pull Request if you'd like to update the library.

**Comment by salagadoola** [comment]
Thanks. I created a pull request for this issue. https://github.com/google/google-toolbox-for-mac/pull/156

**Comment by thomasvl** [comment]
Fixed by #156
