### ISSUE TITLE
 Showing All Messages ld: library not found for -lGTMSessionFetcher

### ISSUE THREAD

**Issue by RameshSain** [google/google-toolbox-for-mac#159]
React-native ios issue.

**Comment by thomasvl** [comment]
I'm not sure what you are trying to report.  Can you provide more information?

**Comment by RameshSain** [comment]
@thomasvl  I am using firebase sdk in react-native project and installing dependency using cocoapods:-
My pod file is like :- 

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ESNext' do
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!
pod 'NewRelicAgent'
pod 'Firebase', '~> 4.0.0'
pod 'Firebase/Crash'
pod 'Firebase/Performance'
#   pod 'React', path: '../node_modules/react-native', :subspecs => [
#   'Core',
#   'RCTActionSheet',
#   'RCTGeolocation',
#   'RCTImage',
#   'RCTLinkingIOS',
#   'RCTNetwork',
#   'RCTSettings',
#   'RCTText',
#   'RCTVibration',
#   'RCTWebSocket'
#   ]
#
#
#    pod 'GoogleMaps'
#    pod 'react-native-maps', :path => '../node_modules/react-native-maps'
#    pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'

#  pod 'RSKImageCropper'
#  pod 'QBImagePickerController'
#pod 'react-native-fetch-blob',
#:path => '../node_modules/react-native-fetch-blob'
# Pods for ESNext

end
post_install do |installer|
installer.pods_project.targets.each do |target|
if target.name == "react-native-google-maps"
target.build_configurations.each do |config|
config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
end
end
end
end

when i try to build or run my project i am getting error of 'library not found '  -lGTMSessionFetcher.
Its headche from last twodays.
please help if possible.

**Comment by thomasvl** [comment]
It sounds like the problem is with one of those other pod then, it is compiling the SessionFetcher directly in instead of using a pod to pull it in.  There isn't anything the SessionFetcher project (https://github.com/google/gtm-session-fetcher) can do to fix things when something else is directly compiling in code instead of using pod dependencies.
