### ISSUE TITLE
Make GoogleToolBoxForMac a static_framework?

### ISSUE THREAD

**Issue by pkrmf** [google/google-toolbox-for-mac#168]
Hey guys! Is there any reason GoogleToolBoxForMac is not a static_framework? It would just take one line in the podspec

**Comment by thomasvl** [comment]
I'll admit, I'm still not clear on if it is needed.  The docs around `static_framework` last time I looked didn't make it immediately clear why it was needed.  Last time I asked, https://github.com/CocoaPods/CocoaPods/issues/7579 got opened to try and help clarify things, but it sorta sounded like most specs shouldn't be using the attribute?
