### ISSUE TITLE
GoogleToolboxForMac is not safe for use in application extensions

### ISSUE THREAD

**Issue by KrisConrad** [google/google-toolbox-for-mac#169]
When including GoogleToolboxForMac in an iOS application extension the following waring is given when creating an Archive build:

ld: warning: linking against a dylib which is not safe for use in application extensions: GoogleToolboxForMac-Defines-NSData+zlib/GoogleToolboxForMac.framework/GoogleToolboxForMac

**Comment by thomasvl** [comment]
How are you building to get this warning?

**Comment by KrisConrad** [comment]
GoogleTooboxForMac is being included via CocoaPods (as a sub-dependency to the Firebase sdk) to an application extension target. Incremental debug builds provide no warnings, only after doing an Archive build (Product -> Archive) do the warnings appear.

**Comment by thomasvl** [comment]
I'm not a cocoapods expert, so I'm not sure if something needs to done on our end or in your setup.  If someone hopefully someone more familiar with cocoapods can chime in with what is needed.

**Comment by KrisConrad** [comment]
From what research I've done it sounds like the warning indicates that there is some API being used that is [not available to iOS app extensions](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html#//apple_ref/doc/uid/TP40014214-CH2-SW6). 

From the warning I'd assume its in the NSData+zlib of Defines header/implementation files. My Objective-C is a bit rusty though and I've been too busy at work to actually dig into the code myself.

**Comment by thomasvl** [comment]
The warning just means the module was compiled without the flag to issue warnings/validate all apis are extension safe (something gets recorded in the final `.a` file).  So the lack of that _info_ is what causes the linker (_ld_) to issue the warning.
