### ISSUE TITLE
Not building in XCode 9 and 10 using the new "New Build System" workspace option

### ISSUE THREAD

**Issue by eriadam** [google/google-toolbox-for-mac#171]
Our app is not building in XCode9 using the new "New Build System" workspace option.

```
[17:45:26]: ▸ :x:  error: unable to build node:
'<MkDir /Users/****/Library/Developer/Xcode/DerivedData/****-agvvhbbeofgmblhecf
hgnulmnxxx/Build/Intermediates.noindex/ArchiveIntermediates/*****/Intermediate
BuildFilesPath/UninstalledProducts/iphoneos/GoogleToolboxForMac.framework/Headers>'
(node is produced by multiple commands; e.g.,
'2092f52c47e4030edbf33bd0e010cbcf04a67f76340ef3625296893937aaf0ab:Debug:MkDir
/Users/****/Library/Developer/Xcode/DerivedData/*****-agvvhbbeofgmblhecfhgnulmnxxx/
Build/Intermediates.noindex/ArchiveIntermediates/*****/IntermediateBuildFilesPath/
UninstalledProducts/iphoneos/GoogleToolboxForMac.framework/Headers' and
'2092f52c47e4030edbf33bd0e010cbcf93ccccb083c871ccd9339690568c10cf:Debug:MkDir
/Users/****/Library/Developer/Xcode/DerivedData/*****-agvvhbbeofgmblhecfhgnulmnxxx/
Build/Intermediates.noindex/ArchiveIntermediates/*****/IntermediateBuildFilesPath/
UninstalledProducts/iphoneos/GoogleToolboxForMac.framework/Headers')
```

**Comment by thomasvl** [comment]
There isn't much to go on here.  Do you use CocoaPods or any other packaging system to add GTM?  Do you directly add/depend on the Xcode project?

The best would be if you could make a repro case with a simple project that shows how you are integrating it and it failing.

**Comment by eriadam** [comment]
Firebase (4.13.0) is installed using Cocapods. GoogleToolboxForMac (2.1.4) is installed as a dependency of that.

When using the "Standard Building System" the project builds fine, switching to the new preview option, it fails with the above error message.

**Comment by thomasvl** [comment]
As long as it seems specific to your set up, maybe see if you can directly depend on GTM and temporarity cut out things to remove any Firebase deps, does it go away then?  If so, what part of the Firebase dependencies triggers it?  etc.  i.e. - working to isolate what seems to cause it is going to help you figure out info others (cocoapods, firebase, or this project) might be doing to cause the problem.

**Comment by airspeed** [comment]
@eriadam 
Were you able to solve this?

**Comment by dotWasim** [comment]
I have same issue! did you figure it out?

**Comment by dotWasim** [comment]
OK, I just removed some pods for test schema and it fixed the issue for me

**Comment by eriadam** [comment]
We had the `Google` pod installed next to `Firebase`. It has been already deprecated for some time, but the `GoogleSignIn` would not work without it. Now it does. And this was not the problem until the new build system.
