### ISSUE TITLE
GTMLoggerInfo and other logging methods output doesn't show up in Console App.

### ISSUE THREAD

**Issue by davidjunhuo** [google/google-toolbox-for-mac#233]
The output messages are not visible from Mac OS console app. NSLog output messages show up. This is very inconvenient for debugging. Please fix it as soon as possible.

**Comment by thomasvl** [comment]
`GTMLogger` uses a `sharedLogger` (singleton), if you don't explicitly configure it, you get some defaults.  It sounds like you might be using the default, but want something different.  Just use `setSharedLogger` to provide one configured how your application wants (levels, filtering, etc.).
