### ISSUE TITLE
GTMGoogleTestRunner: SetupTestCase, TearDownTestCase are executed for every test function

### ISSUE THREAD

**Issue by rmstar** [google/google-toolbox-for-mac#242]
SetupTestCase, TearDownTestCase are expected to be executed once per test suite. However, when C++ unit tests are run on iOS using GTMGoogleTestRunner, SetupTestCase and TearDownTestCase are run once per test function. 

I have more details with repro steps and test logs on internal bug 138226843.

**Comment by thomasvl** [comment]
This is a limitation when trying to bridge the two different testing models, #243 updated the sources to document things.
