### ISSUE TITLE
XCode 10 Test Navigator shows no tests with GTMGoogleTestRunner

### ISSUE THREAD

**Issue by TheSlowGrowth** [google/google-toolbox-for-mac#246]
I'm using XCode 10.3 to build a cross-platform C++ application that uses GoogleTests. The project is based on CMake but I don't think this is important to my problem.

The contents of my project file:
- An app bundle that is basically a console application that runs the typical GoogleTest main(). It's an app bundle only to be able to generate an XCTest target for it. It contains multiple source files with tests
- A `macOS Unit Testing Bundle` that has the app bundle set as its testee and also builds `GTMGoogleTestRunner.mm`

The Testing Bundle builds and runs all my tests, but none of them appear in the XCode Test Navigator. All I see there is `GTMGoogleTestRunner` with no tests in it.

What could be the problem here?

**Comment by thomasvl** [comment]
Xcode's UI works pare scanning the sources, so it only knows how to look for _true_ XCTests and since the actually tests are created dynamically at runtime Xcode doesn't have a way to get them exposed (just the log results will have them).

**Comment by TheSlowGrowth** [comment]
Did that change in the past? I see several blog posts that indicate that it should have been working just fine in the past. Right now, the whole `GTMGoogleTestRunner.mm` seems a bit useless to me.

Is there any other way to use the Test Navigator in XCode? Right now, it seems extremely tedious to work with larger projects that have many gtests in them. I could
1. Run the gtest main() in the debugger and wait until the test I'm working on is executed (This can take a while with large projects)
2. Use the gtest command line arguments to run just a single test (this is tedious)
3. Exclude all tests except the one I'm working on from the build (also very tedious)
4. Manually add an XCTest class for each of my gtests (a pain to maintain and enforce)

Are there other options?

**Comment by thomasvl** [comment]
@dmaclach

**Comment by ingjieye** [comment]
Is there a solution for this?
