### ISSUE TITLE
GTMStringEncoding deprecated methods should be unavailable in Swift. 

### ISSUE THREAD

**Issue by stefanamiller** [google/google-toolbox-for-mac#248]
The deprecated methods cause conflicts in the generated interface of the newer methods that would add a zero-length tuple parameter.

Example: Current generated methods for `encode:error:`:

```
@available(*, deprecated, message: "Use encode:error:")
open func encode(_ data: Data!) -> String!

open func encode(_ data: Data!, error: ()) throws -> String
```

**Comment by thomasvl** [comment]
Looks like the real question is why is the tuple there since it is remapping to one that throws correctly?

**Comment by stefanamiller** [comment]
The tuple is there because the deprecated method has the same signature as the one that would be auto-generated. I've verified that the interface cleans this up for my pull request.
