### ISSUE TITLE
Bazel Support

### ISSUE THREAD

**Issue by cpsauer** [google/google-toolbox-for-mac#266]
Thank you all so much for a wonderful library!

I was wondering if there's any chance you'd consider releasing an official BUILD file, so this can can easily be used with Bazel. I'm operating under the assumption that there's probably one hanging around internally :)

Sincerely,
Former Googler eager to use GTM with Bazel :)

**Comment by thomasvl** [comment]
What's needed internally at Google and externally isn't always an exact match. Google using a mono repo, meaning things end up being somewhat different.  The lack of a package manager for bazel also means a bazel setup needs something done to play nicely with the external repositories for rules (the hook to add to WORKSPACES, etc.).  But if someone wants to try to craft one, I guess we could look at accepting it.

**Comment by tinder-maxwellelliott** [comment]
@thomasvl This can be closed now?

**Comment by thomasvl** [comment]
Yup.

Fixed via #280
