### ISSUE TITLE
Don't fail SKIPPED tests, e.g. support GTEST_SKIP.

### ISSUE THREAD

**Issue by strangewiz** [google/google-toolbox-for-mac#300]
Currently when running a gtest via GTMGoogleTestRunner.mm, [  SKIPPED ] tests are considered failures.

This appears to be because OnTestPartResult checks `test_part_result.passed()`, which appears to mean !failed && !skipped.

**Comment by thomasvl** [comment]
Fixed via https://github.com/google/google-toolbox-for-mac/pull/308
