### ISSUE TITLE
Insecure API when using in React Native iOS app

### ISSUE THREAD

**Issue by master4-2021** [google/google-toolbox-for-mac#368]
There are some insecure APIs that exists in this repository that Apple considered insecure and recommended not using:
https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/Articles/BufferOverflows.html#//apple_ref/doc/uid/TP40002577-SW1

These are reported when using Mobile Security Framework (https://github.com/MobSF/Mobile-Security-Framework-MobSF) to scan the IPA.

strlen:

https://github.com/google/google-toolbox-for-mac/blob/e68733fbef9154a28c682645da33c25d6689d78d/DebugUtils/GTMDebugSelectorValidation.h#L61
https://github.com/google/google-toolbox-for-mac/blob/e68733fbef9154a28c682645da33c25d6689d78d/DebugUtils/GTMDebugSelectorValidation.h#L81

https://github.com/google/google-toolbox-for-mac/blob/094f773908cd3914b5bf18bce1fd4d84a9311e10/DebugUtils/GTMDebugThreadValidation.h#L43
https://github.com/google/google-toolbox-for-mac/blob/094f773908cd3914b5bf18bce1fd4d84a9311e10/Foundation/GTMStringEncoding.m#L271
https://github.com/google/google-toolbox-for-mac/blob/094f773908cd3914b5bf18bce1fd4d84a9311e10/Foundation/GTMSQLiteTest.m#L1294
https://github.com/google/google-toolbox-for-mac/blob/094f773908cd3914b5bf18bce1fd4d84a9311e10/Foundation/GTMSQLiteTest.m#L1485

I understand that the use of these function does not definitely leads to security issues, but I want to bring this to your attention, and check if these are safe to use within our application.

**Comment by thomasvl** [comment]
Two of the `strlen` calls are within testing code for this library and not with the library code itself.

The `strlen` within GTMStringEncoding.h is an api explicitly taking a c-string, so the call is correct/fine (along with the used value).

The `strlen` within GTMDebugThreadValidation.h is safe for the usage, it is also debug code. Reality is the length isn't fully needed, this could be tweaks to check for a zero length directly if someone wants to submit a PR.

The two `strlen` calls within GTMDebugSelectorValidation.h are both correct in their usage as they are on c-string arguments to the functions, and there aren't other ways to do the same work.
