### ISSUE TITLE
App Store submission issue detected for privacy manifest

### ISSUE THREAD

**Issue by akships** [google/google-toolbox-for-mac#467]
Hi, 

I receive the following message from Apple after app submission to app store
<img width="771" alt="privacy-apple" src="https://github.com/user-attachments/assets/6fdfbd27-1c11-4aba-ba50-390df6556e47">

Any ideas how to solve this please ? 

PS : bundle version of package is 2.3.2

**Comment by thomasvl** [comment]
2.3.2 is from August of 2022, so it's pretty old (predates all of privacy manifest requirements from apple)

The 4.2.0 release from January (of 2024) included the xcprivacy manifest information. So you'll need to move up to that, or figure out the manifest for that old version.
