### ISSUE TITLE
Missing privacy manifest

### ISSUE THREAD

**Issue by mfae** [google/google-toolbox-for-mac#487]
Hello,
we are using the @capacitor-mlkit/barcode-scanning plugin in our project. And Apple warns us, that it will reject it in the future for privacy reasins. Maybe you can help?

I found this:
https://github.com/renovate-bot/google-_-google-toolbox-for-mac/commit/c563afa079cf09b162bf8b97ddd0c99e61bc3424

But I don't know how to integrate it into our project.

And Apple seems to have a problem finding the correct privacy manifest. They send us this email when submitting our app:

> Although submission for App Store review was successful, you may want to correct the following issues in your next submission for App Store review. Once you've corrected the issues, upload a new binary to App Store Connect.
> 
> ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/GoogleToolboxForMac.framework/GoogleToolboxForMac”, which includes GoogleToolboxForMac, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting February 12, 2025, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a privacy manifest file. **Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest.** For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.

Looking forward to your reply,

Alex

**Comment by thomasvl** [comment]
You must be pulling in a version before the 4.2.0 Release (but you want the 4.2.1 or higher; that was the first release to include the manifest.  Full [Releases info](https://github.com/google/google-toolbox-for-mac/releases). So you'll need to update your dependencies and/or what ever transitive dependencies to ensure they aren't forcing a lower version.
