### ISSUE TITLE
Request for Information on Privacy Manifest for GoogleToolboxForMac

### ISSUE THREAD

**Issue by Jesus-Escala** [google/google-toolbox-for-mac#495]
Hello,

I am a developer of the application TSI Rendiciones (Version 1.2.0, Build 4) and recently submitted the app for review on the App Store. However, I received an error message (ITMS-91061) indicating that the privacy manifest is missing for the GoogleToolboxForMac SDK included in my application.

The message from the App Store states that starting February 12, 2025, any SDK that affects privacy must include a privacy manifest file. I would like to know if there is an updated version of GoogleToolboxForMac that includes this manifest, or if there is any procedure I should follow to comply with this requirement.

I appreciate any information you can provide regarding this matter, as it is crucial for me to continue with the review process of my application.

Best regards,

Jesus Escala
jesusescalatrabajo@gmail.com

**Comment by thomasvl** [comment]
Duplicate #487
